server:
  port: 0
spring:
  artemis: #ActiveMQ Artemis
    host: tcp://localhost:61616
    user: admin
    password: admin
    mode: native
  jms:
    template:
      default-destination: taco.order.queue
some:
  specific:
    taco-client:
      configuration: this-is-my-configuration
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka