spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: taco-reactive

server:
  port:
    8090
some:
  specific:
    Taco-Reactive-API:
      configuration: this-is-my-Taco-Reactive-API-configuration

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka